version: v1
kind: kubernetes
application: buildyou

targets:
  staging:
    account: docker-desktop
    namespace: staging
    strategy: rolling
  prod:
    account: docker-desktop
    namespace: prod
    strategy: trafficSplit
    constraints:
      dependsOn: ["staging"]
      beforeDeployment:
        - pause:
            untilApproved: true
manifests:
  - path: manifests/namespace-staging.yaml
    targets: ["staging"]
  - path: manifests/namespace-prod.yaml
    targets: ["prod"]

strategies:
  rolling:
    canary:
      steps:
        - setWeight:
            weight: 100
  trafficSplit:
    canary:
      steps:
        - setWeight:
            weight: 50
        - pause:
            untilApproved: true
        - setWeight:
            weight: 100